version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev


  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: mydb
  #   ports:
  #     - "5432:5432"
